spring:
  application:
    name: file
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:9003
server:
  port: 9003
servlet:
  multipart:
    max-file-size: 20480000000
classpath_mapping:
  classpath:/META-INF/resources/
url_mapping:
  file:/Users/xuyuanfeng/file/
file_upload_path:
  /Users/xuyuanfeng/file/