eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: gateway
server:
  port: 8088
zuul:
  routes:
    service: /service/0/**
    service2: /service/1/**

